version: '3.3'
services:
    api:
        image: 'shlinkio/shlink:stable'
        restart: unless-stopped
        environment:
            DEFAULT_DOMAIN: ${API_URL}
            IS_HTTPS_ENABLED: true
            BYPASS_LITESTREAM: ${BYPASS_LITESTREAM}
            #GEOLITE_LICENSE_KEY: kjh23ljkbndskj345
        volumes:
            - ./litestream.yml:/etc/litestream.yml
            - ./database/database.sqlite:/etc/shlink/data/database.sqlite
            - ./database/database.sqlite-shm:/etc/shlink/data/database.sqlite-shm
            - ./database/database.sqlite-wal:/etc/shlink/data/database.sqlite-wal
        labels:
           caddy: ${API_URL}
           caddy.reverse_proxy: "{{upstreams 8080}}"
        ports:
            - ${API_PORT}:8080
        networks:
            caddy:
                aliases:
                    - "shlink-api"
            
    litestream:
        image: 'litestream/litestream'
        restart: unless-stopped
        working_dir: /usr/local/bin/
        entrypoint: /bin/sh
        command: >
            -c "\
                /usr/local/bin/litestream restore -if-replica-exists -if-db-not-exists /data/database.sqlite && \
                /usr/local/bin/litestream replicate \
                "
        environment:
            R2_BUCKET: ${R2_BUCKET}
            R2_ACCESS_KEY: ${R2_ACCESS_KEY}
            R2_SECRET_KEY: ${R2_SECRET_KEY}
            R2_DATA_PATH: ${R2_DATA_PATH}
            R2_URL: ${R2_URL}
        volumes:
            - ./litestream.yml:/etc/litestream.yml
            - ./database/:/data/
            
    web:
        image: shlinkio/shlink-web-client
        restart: unless-stopped
        ports:
            - ${WEB_PORT}:80
        labels:
           caddy: paste-web.tomekwaller.com
           caddy.reverse_proxy: "{{upstreams 80}}"
        environment:
            SHLINK_SERVER_API_KEY: ${SHLINK_SERVER_API_KEY}
            SHLINK_SERVER_NAME: "${SHLINK_SERVER_NAME}"
            SHLINK_SERVER_URL: "https://${API_URL}"
            DEFAULT_DOMAIN: ${API_URL}
            # - IS_HTTPS_ENABLED=true
            # - GEOLITE_LICENSE_KEY=kjh23ljkbndskj345
        networks:
            caddy:
                aliases:
                    - "shlink-web"

networks:
  caddy:
    external: true
